name: Sends a Slack notification on Pull Request creation

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  post_slack_message:
    runs-on: ubuntu-20.04
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
